// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_snapshots.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, user_id, amount, as_of_date, created_at
FROM balance_snapshots
WHERE user_id = $1
ORDER BY as_of_date DESC
    LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, userID uuid.UUID) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, userID)
	var i BalanceSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AsOfDate,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSnapshotAtOrBefore = `-- name: GetLatestSnapshotAtOrBefore :one
SELECT id, user_id, amount, as_of_date, created_at
FROM balance_snapshots
WHERE user_id = $1 AND as_of_date <= $2
ORDER BY as_of_date DESC
    LIMIT 1
`

type GetLatestSnapshotAtOrBeforeParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	AsOfDate pgtype.Date `json:"as_of_date"`
}

func (q *Queries) GetLatestSnapshotAtOrBefore(ctx context.Context, arg GetLatestSnapshotAtOrBeforeParams) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotAtOrBefore, arg.UserID, arg.AsOfDate)
	var i BalanceSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AsOfDate,
		&i.CreatedAt,
	)
	return i, err
}

const upsertBalanceSnapshot = `-- name: UpsertBalanceSnapshot :one
INSERT INTO balance_snapshots (user_id, amount, as_of_date)
VALUES ($1, $2, $3)
    ON CONFLICT (user_id, as_of_date)
DO UPDATE SET amount = EXCLUDED.amount, created_at = now()
           RETURNING id, user_id, amount, as_of_date, created_at
`

type UpsertBalanceSnapshotParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Amount   pgtype.Numeric `json:"amount"`
	AsOfDate pgtype.Date    `json:"as_of_date"`
}

func (q *Queries) UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertBalanceSnapshot, arg.UserID, arg.Amount, arg.AsOfDate)
	var i BalanceSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.AsOfDate,
		&i.CreatedAt,
	)
	return i, err
}
