// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceSnapshot struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Amount    pgtype.Numeric `json:"amount"`
	AsOfDate  pgtype.Date    `json:"as_of_date"`
	CreatedAt time.Time      `json:"created_at"`
}

type ExpenseObligation struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Amount         pgtype.Numeric     `json:"amount"`
	DayOfMonth     int16              `json:"day_of_month"`
	OverflowPolicy string             `json:"overflow_policy"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type IncomeSource struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Amount         pgtype.Numeric     `json:"amount"`
	DayOfMonth     int16              `json:"day_of_month"`
	OverflowPolicy string             `json:"overflow_policy"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type SavingsBucket struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Name          string         `json:"name"`
	TargetAmount  pgtype.Numeric `json:"target_amount"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	CreatedAt     time.Time      `json:"created_at"`
}

type SavingsRule struct {
	ID             uuid.UUID      `json:"id"`
	IncomeSourceID uuid.UUID      `json:"income_source_id"`
	BucketID       uuid.UUID      `json:"bucket_id"`
	Mode           string         `json:"mode"`
	Value          pgtype.Numeric `json:"value"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Transaction struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	Type                string             `json:"type"`
	Amount              pgtype.Numeric     `json:"amount"`
	TxnDate             pgtype.Date        `json:"txn_date"`
	Status              string             `json:"status"`
	IncomeSourceID      pgtype.UUID        `json:"income_source_id"`
	ExpenseObligationID pgtype.UUID        `json:"expense_obligation_id"`
	SavingsRuleID       pgtype.UUID        `json:"savings_rule_id"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           time.Time          `json:"created_at"`
	ConfirmedAt         pgtype.Timestamptz `json:"confirmed_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
