// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) (ConfirmTransactionRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetActiveExpenseObligations(ctx context.Context, userID uuid.UUID) ([]GetActiveExpenseObligationsRow, error)
	GetActiveIncomeSources(ctx context.Context, userID uuid.UUID) ([]GetActiveIncomeSourcesRow, error)
	GetActiveSavingsRulesForUser(ctx context.Context, userID uuid.UUID) ([]GetActiveSavingsRulesForUserRow, error)
	GetConfirmedTransactionsInRange(ctx context.Context, arg GetConfirmedTransactionsInRangeParams) ([]Transaction, error)
	GetLatestSnapshot(ctx context.Context, userID uuid.UUID) (BalanceSnapshot, error)
	GetLatestSnapshotAtOrBefore(ctx context.Context, arg GetLatestSnapshotAtOrBeforeParams) (BalanceSnapshot, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) (BalanceSnapshot, error)
}

var _ Querier = (*Queries)(nil)
