// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveExpenseObligations = `-- name: GetActiveExpenseObligations :many
SELECT id, user_id, name, amount, day_of_month, overflow_policy, created_at
FROM expense_obligations
WHERE user_id = $1 AND archived_at IS NULL
`

type GetActiveExpenseObligationsRow struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	DayOfMonth     int16          `json:"day_of_month"`
	OverflowPolicy string         `json:"overflow_policy"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) GetActiveExpenseObligations(ctx context.Context, userID uuid.UUID) ([]GetActiveExpenseObligationsRow, error) {
	rows, err := q.db.Query(ctx, getActiveExpenseObligations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveExpenseObligationsRow
	for rows.Next() {
		var i GetActiveExpenseObligationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.OverflowPolicy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveIncomeSources = `-- name: GetActiveIncomeSources :many
SELECT id, user_id, name, amount, day_of_month, overflow_policy, created_at
FROM income_sources
WHERE user_id = $1 AND archived_at IS NULL
`

type GetActiveIncomeSourcesRow struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	DayOfMonth     int16          `json:"day_of_month"`
	OverflowPolicy string         `json:"overflow_policy"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) GetActiveIncomeSources(ctx context.Context, userID uuid.UUID) ([]GetActiveIncomeSourcesRow, error) {
	rows, err := q.db.Query(ctx, getActiveIncomeSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveIncomeSourcesRow
	for rows.Next() {
		var i GetActiveIncomeSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.OverflowPolicy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSavingsRulesForUser = `-- name: GetActiveSavingsRulesForUser :many
SELECT
    sr.id, sr.income_source_id, sr.bucket_id, sr.mode, sr.value, sr.created_at,
    sb.name AS bucket_name, sb.target_amount, sb.current_amount
FROM savings_rules sr
         JOIN savings_buckets sb ON sr.bucket_id = sb.id
         JOIN income_sources ins ON sr.income_source_id = ins.id
WHERE ins.user_id = $1 AND ins.archived_at IS NULL
`

type GetActiveSavingsRulesForUserRow struct {
	ID             uuid.UUID      `json:"id"`
	IncomeSourceID uuid.UUID      `json:"income_source_id"`
	BucketID       uuid.UUID      `json:"bucket_id"`
	Mode           string         `json:"mode"`
	Value          pgtype.Numeric `json:"value"`
	CreatedAt      time.Time      `json:"created_at"`
	BucketName     string         `json:"bucket_name"`
	TargetAmount   pgtype.Numeric `json:"target_amount"`
	CurrentAmount  pgtype.Numeric `json:"current_amount"`
}

func (q *Queries) GetActiveSavingsRulesForUser(ctx context.Context, userID uuid.UUID) ([]GetActiveSavingsRulesForUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveSavingsRulesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSavingsRulesForUserRow
	for rows.Next() {
		var i GetActiveSavingsRulesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.IncomeSourceID,
			&i.BucketID,
			&i.Mode,
			&i.Value,
			&i.CreatedAt,
			&i.BucketName,
			&i.TargetAmount,
			&i.CurrentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
