// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTransaction = `-- name: ConfirmTransaction :one
UPDATE transactions
SET status = 'confirmed', confirmed_at = now(), amount = COALESCE($3, amount)
WHERE id = $1 AND user_id = $2 AND status = 'planned'
    RETURNING id, user_id, type, amount, txn_date, status, confirmed_at
`

type ConfirmTransactionParams struct {
	ID     uuid.UUID      `json:"id"`
	UserID uuid.UUID      `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

type ConfirmTransactionRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Type        string             `json:"type"`
	Amount      pgtype.Numeric     `json:"amount"`
	TxnDate     pgtype.Date        `json:"txn_date"`
	Status      string             `json:"status"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) (ConfirmTransactionRow, error) {
	row := q.db.QueryRow(ctx, confirmTransaction, arg.ID, arg.UserID, arg.Amount)
	var i ConfirmTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.TxnDate,
		&i.Status,
		&i.ConfirmedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, type, amount, txn_date, status,
    income_source_id, expense_obligation_id, savings_rule_id, note
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, user_id, type, amount, txn_date, status, created_at
`

type CreateTransactionParams struct {
	UserID              uuid.UUID      `json:"user_id"`
	Type                string         `json:"type"`
	Amount              pgtype.Numeric `json:"amount"`
	TxnDate             pgtype.Date    `json:"txn_date"`
	Status              string         `json:"status"`
	IncomeSourceID      pgtype.UUID    `json:"income_source_id"`
	ExpenseObligationID pgtype.UUID    `json:"expense_obligation_id"`
	SavingsRuleID       pgtype.UUID    `json:"savings_rule_id"`
	Note                pgtype.Text    `json:"note"`
}

type CreateTransactionRow struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Type      string         `json:"type"`
	Amount    pgtype.Numeric `json:"amount"`
	TxnDate   pgtype.Date    `json:"txn_date"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.TxnDate,
		arg.Status,
		arg.IncomeSourceID,
		arg.ExpenseObligationID,
		arg.SavingsRuleID,
		arg.Note,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.TxnDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getConfirmedTransactionsInRange = `-- name: GetConfirmedTransactionsInRange :many
SELECT
    id, user_id, type, amount, txn_date, status,
    income_source_id, expense_obligation_id, savings_rule_id, note, created_at, confirmed_at
FROM transactions
WHERE user_id = $1
  AND status IN ('confirmed', 'manual')
  AND txn_date >= $2
  AND txn_date <= $3
ORDER BY txn_date ASC
`

type GetConfirmedTransactionsInRangeParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TxnDate   pgtype.Date `json:"txn_date"`
	TxnDate_2 pgtype.Date `json:"txn_date_2"`
}

func (q *Queries) GetConfirmedTransactionsInRange(ctx context.Context, arg GetConfirmedTransactionsInRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getConfirmedTransactionsInRange, arg.UserID, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.TxnDate,
			&i.Status,
			&i.IncomeSourceID,
			&i.ExpenseObligationID,
			&i.SavingsRuleID,
			&i.Note,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
